[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NODE_VERSION = "22.18.0"

[functions]
node_bundler = "esbuild"


[[redirects]]
from = "/mcp/*"
to = "/.netlify/functions/mcpServer/:splat"
status = 200
force = true
