[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22.15.1"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/mcp/*"
  to = "/.netlify/functions/startMcpServer/:splat"
  status = 200
  force = true